#!/bin/bash

rsync -a -v -z -r -e "ssh -vv" --progress --delete ./public/* jjwmezun@boskeopolis-land.com:/usr/share/nginx/boskeopolis-land/public
rsync -a -v -z -r -e "ssh -vv" --progress --delete ./src/* jjwmezun@boskeopolis-land.com:/usr/share/nginx/boskeopolis-land/src
rsync -a -v -z -r -e "ssh -vv" --progress --delete ./vendor/* jjwmezun@boskeopolis-land.com:/usr/share/nginx/boskeopolis-land/vendor
scp composer.json jjwmezun@boskeopolis-land.com:/usr/share/nginx/boskeopolis-land/composer.json
scp composer.lock jjwmezun@boskeopolis-land.com:/usr/share/nginx/boskeopolis-land/composer.lock
